config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :forms, only: :create
  resources :recs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/rec.rb
class Rec < ApplicationRecord
  has_one_attached :photo
  acts_as_taggable_on :tags

  scope :all_books, -> { where(category: "Book") }
  scope :all_movies, -> { where(category: "Movie") }
  scope :all_shows, -> { where(category: "Show") }
  scope :all_fanfics, -> { where(category: "Fanfic") }
  scope :all_games, -> { where(category: "Game") }
  scope :all_misc, -> { where(category: "Misc") }

  def rec_types
    ["Book", "Movie", "Show", "Fanfic", "Game", "Misc"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  
  def create
    @form = Form.new(form_params)
    if @form.save
      UserMailer.contact(@form).deliver_now
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  private

  def form_params 
    params.require(:form).permit(:first_name, :last_name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
    @form = Form.new
  end
end

app/controllers/recs_controller.rb
class RecsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_rec, only: [:show, :destroy, :edit, :update]

  def create
    @rec = Rec.new(rec_params)
    if @rec.save 
      redirect_to recs_path
    else
      render :new
    end
  end
  
  def new
    @rec = Rec.new
  end

  def index
    @recs = Rec.all
  end

  def show
  end

  def edit
  end

  def update
    @rec.update(rec_params)
    redirect_to recs_path
  end

  def destroy
    @rec.destroy
    redirect_to recs_path
  end

  private

  def find_rec
    @rec = Rec.find(params[:id])
  end

  def rec_params
    params.require(:rec).permit(:creator, :synopsis, :title, :why, :imdb_rating, :rt_rating, :release_date, :photo, :link, :duration, :category, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Directtoanne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('icon.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div id="particles-js"></div><script src="particles.js"></script>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_contact_form.html.erb
<br>
<div class="form-box">
  <%= simple_form_for @form, html: { autocomplete: 'off' } do |f| %>
    <div class="row">
      <div class="col">
        <%= f.input :first_name %>
      </div>
      <div class="col">
        <%= f.input :last_name %>
      </div>
    </div>
    <%= f.input :email %>
    <%= f.input :message, :input_html => {:rows => 5} %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<br>
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <%= image_tag "profile.png", class: "profile-image" %>
    <div class="ml-4">
      <div class="d-flex mb-2">
        <h1>Hi, I'm Anne.</h1>
      </div>
      <div class="d-flex">
        <p>I learned to code after I fell in love with text-based games like Zork, A Dark Room, and Candy Box. With just a few languages under my belt, I'm technically still a baby to the big bad world of web development, but I'm slowly learning my way through PHP, Swift and Lua (when I'm not getting distracted writing movie reviews or scripts to choice-based games).</p>
      </div>
      <div class="d-flex">
        <p>Most of the websites I've built are apps on Ruby on Rails & React, or static HTML/CSS landing pages for companies branching into the digital market who need to establish a lasting web presence. You can see some of my work below, or if you prefer something more fun - you can check out my recommendations for an endless and perpetually-growing list of ways to waste time.</p>
      </div>
      <div class="d-flex mt-2 justify-content-around anne-links">
        <%= link_to "https://github.com/directtoanne", class: "", target: :_blank do %>
          <i class="fab fa-github"></i>
        <% end %>
        <%= link_to "https://letterboxd.com/directtoanne/", class: "", target: :_blank do %>
          <div class="image-overlay">
            <%= image_tag "letterboxd-mac-icon (1) (2).png", class: "icon-letterboxd" %>
            <%= image_tag "letterboxd-mac-icon (1) (3).png", class: "icon-letterboxd overlayed-image" %>
          </div>
        <% end %>
        <%= link_to "https://www.instagram.com/directtoanne/", class: "", target: :_blank do %>
          <i class="fab fa-instagram mr-4"></i>
        <% end %>
        <div class="transparent ml-4">
          <i class="fab fa-youtube ml-4"></i>
          <i class="fab fa-twitter ml-4"></i>
          <i class="fab fa-linkedin ml-4"></i>
          <i class="fab fa-twitch ml-4"></i>
          <i class="fab fa-facebook ml-4"></i>
          <i class="fab fa-reddit ml-4"></i>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="d-flex mt-4">
    <h1 id="projects">My Projects:</h1>
  </div>
</div>

<div class="container-fluid project-grid text-center">
  <%= link_to "https://www.fin-man.xyz", class: "p-3", target: :_blank do %>
    <div class="project-hover">
      <%= image_tag "finman.png", class: "project-card" %>
      <div class="overlay">
        <div class="text-overlay">Fin-Man is a financial management (see the pun?) app, made entirely on Ruby on Rails. The biggest challenge was learning to find and integrate the correct gems for our app, some of which relied on dependencies that were out of date and no longer maintained.<br>In the end, we didn't manage to code all the features we wanted, but it was still a great and rewarding experience considering we only had a couple weeks to finish it.</div>
      </div>
    </div>
  <% end %>
  <%= link_to "https://airbnb-caravan.herokuapp.com/", class: "p-3", target: :_blank do %>
    <div class="project-hover">
      <%= image_tag "caravan.png", class: "project-card" %>
      <div class="overlay">
        <div class="text-overlay">Caravan is just another Airbnb clone, except instead of flats the idea was to rent - you guessed it! - cars. As my first team Rails project, it was a steep learning curve to discover how to delegate tasks and collaborate on features we all had conflicting ideas about. Being responsible for individual features was an experience I hadn't had as a sole developer, and definitely taught me the importance of writing clear and clean code.</div>
      </div>
    </div>
  <% end %>
  <%= link_to "https://directtoanne.github.io/thesgboys/", class: "p-3", target: :_blank do %>
    <div class="project-hover">
      <%= image_tag "sgboys.png", class: "project-card" %>
      <div class="overlay">
        <div class="text-overlay">The SG Boys were an LGBT podcast based in the little red conservative dot where homosexuality is still (politically) illegal. This was a static website written entirely in HTML and CSS. My challenge was to do this entirely without using Bootstrap or other frameworks for the layouts / utilities / grids. Though I managed to make it look (reasonable) on desktops, I never made the website responsive for smaller screens.</div>
      </div>
    </div>
  <% end %>
  <%= link_to "https://directtoanne.github.io/profile/", class: "p-3", target: :_blank do %>
    <div class="project-hover">
      <%= image_tag "anne.png", class: "project-card" %>
      <div class="overlay">
        <div class="text-overlay">My first static website ever was a simple card layout for my own profile. </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
<br>
<div class="container mt-3">
  <div class="d-flex">
    <h1>Feedback from Happy Clients:</h1>
  </div>
  <div class="d-flex mt-4 justify-content-around">
    <div class="text-right">
      <%= image_tag "kwang.png", class: "speech-card" %>
      <h2>- Kennede Sng</h2>
    </div>
    <div class="text-right">
      <%= image_tag "omar.png", class: "speech-card" %>
      <h2>- Omar Michael</h2>
      <h5>(missing for the past 36 hours)</h5>
    </div>
    <div class="text-right">
      <%= image_tag "mom.png", class: "speech-card" %>
      <h2>- her mother</h2>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div class="container mt-3">
  <div class="d-flex">
    <h1 id="faq">Frequently Asked Questions:</h1>
  </div>

  <div class="text-left mt-4">
    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Why Should We Work With You?
            </button>
          </h5>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <p>You probably shouldn't. I'm only half-kidding. The truth is that most businesses can get by with a simple Wordpress or Squarespace website, which are easy enough to use that even the tech-illiterate can make a legible-enough landing page. There are drag and drop website builders like Wix littered across the Internet, that sell you on the fact that you too! Can make your own website.</p>
            <br><div class="d-flex"><p>And there's nothing wrong with that at all.</p></div>
            <br><p>What I absolutely detest, though, is seeing "Wordpress developers" or "Elementor designers" who don't actually know how to code, taking advantage of potential clients who don't know much about what goes into the backend of code, and charging them <em>thousands</em>, even <em>tens of thousands</em> for a website they didn't actually <b>write</b>, they just made use of a drag and drop library to arrange elements in a good-looking-enough package.</p>
            <br>
            <p>The problem is most people running SMEs are so busy/non-tech-savvy that they don't realize they're being overcharged, or worse: they know that they are, but would rather shell out thousands out of convenience. And then those "devs" add on maintenance charges, marketing/advertisement charges, and domain/ssl registration charges that are ten times more expensive than what they should actually cost.</p>
            <br>
            <p>Long story short, if you were planning on hiring some dodgy freelance "dev" who spits words like "Beautiful", "Fast" and "Responsive" like they're watering crops during a drought, namedrops site-builders like Oxygen and Elementor (and not the programming <em>languages</em> employed themselves), then you're better off with me.</p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              How Long Will It Take?
            </button>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">
            <p>I don't subscribe to the advertising strategies of other web devs who like to flaunt "a site within a week" promises or provide a 24-hour-static-site-guarantee. The truth is: it really depends. A social media website like Facebook would take longer to code than a blog. An online marketplace like Etsy would take longer to set up, maintain and market than a simple landing page with a booking form for a restaurant.</p><br>
            <p>As a benchmark, this website itself took me around a day to code and host (minus the recommendations tab), but that's because I already knew <em>what</em> I wanted it to look like, and I am also completely complicit with full control over my own brand image. A lot of the length of a project isn't actually spent coding, it's spent brainstorming and deciding the final features/look of the product itself. In other words, if you know <em>exactly</em> what the site should look like from the get go, the process is going to go much faster. Sketches/examples of other websites would also greatly speed up the process.</p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              How Much Will It Cost?
            </button>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body">
            <p>Ah, the big question. Once again, it really depends. For a start, domains/hosting/certificates can vary wildly in price. A domain that ends in '.xyz' or '.net' might cost $2 for a two-year license while its equivalent that ends in '.com' or '.co.uk' may cost up to thousands; similarly, a specific domain like 'anaboutiquelondon.com' would be much cheaper than 'anaboutique.com'.</p><br>
            <p>Additionally, SSL certification for your website (meaning your site is secure - 'https://' rather than 'http://' - and your browser has the little lock symbol in the top left) has different tiers - a basic SSL certificate is under $10, but if you plan on authorizing online payments or hosting secure chatrooms, the higher tiers are preferred - if not, necessary.</p><br>
            <p>There are many more facets similar to this; I won't bore you with the specifics of Google Adwords and search engine optimization, but I will say that the cost for a simple static website should only cost a few hundred. Unless you're planning on absolutely buying up the best keywords on search engines and enabling crazy features like full-AI-chatbots (though I couldn't imagine what for, if it's just a normal landing site), a simple website should only go up to a thousand six hundred <b>at the most</b>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div class="container mt-2">
  <div class="d-flex">
    <h1 id="contact">Contact Me:</h1>
  </div>
  <div class="d-flex mt-4">
    <h5>Want to work with me? Are you sure?! Fill in the form below and I'll be in touch!</h5>
  </div>
  <div id="contact">
    <%= render 'contact_form' %>
  </div>
</div>

app/views/recs/_card.html.erb
<div class="container d-flex">
  <% if rec.photo.attached? %>
    <%= cl_image_tag rec.photo.key, class: "show-image" %>
  <% end %>
  <div class="ml-4 show-rec-card">
    <% if ['Show', 'Movie'].include? rec.category %>
      <div class="d-flex justify-content-between">
        <div class="mr-4 pr-4">
          <h1><%= rec.title %></h1>
          <h6><%= rec.creator %></h6>
        </div>
        <div class="ml-4 mt-2 pl-4 text-right">
          <h6>Year: <%= rec.duration %></h6>
          <h6>IMDB: <%= rec.imdb_rating %>/10</h6>
          <h6>Rotten Tomatoes: <%= rec.rt_rating %>%</h6>
        </div>
      </div>
    <% else %>
      <div class="d-flex justify-content-between">
        <div class="mr-4 pr-4">
          <h1><%= rec.title %></h1>
          <h6><%= rec.creator %></h6>
        </div>
        <div class="ml-4 mt-2 pl-4 text-right">
          <h6>Year: <%= rec.duration %></h6>
        </div>
      </div>
    <% end %>
    <h3 class="mt-4">Synopsis:</h3>
    <%= rec.synopsis %>
    <h3 class="mt-4">Why you should give it a shot:</h3>
    <%= rec.why %>
    <br><br>
    <%= link_to edit_rec_path(rec) do %>
      <button>Edit Rec!</button>
    <% end %>
  </div>
</div>

app/views/recs/_filter.html.erb
<div class="container d-flex flex-wrap justify-content-around" id="accordion">
  <% @recs.each do |rec| %>
    <% if rec.photo.attached? %>
      <div class="rec-overlay">
        <%= cl_image_tag rec.photo.key, class: "index-image mt-4" %>
        <div class="card-overlay text-center d-flex align-items-center justify-content-around">
          <a data-toggle="collapse" href="#collapse-<%=rec.id%>" role="button" aria-expanded="false" aria-controls="#collapse-<%=rec.id%>">
            <i class="fas fa-eye"></i>
          </a>
          <%= link_to rec.link, target: :_blank do %>
            <i class="fas fa-link"></i>
          <% end %>
        </div>
      </div>

      <div class="collapse" id="collapse-<%=rec.id%>" data-parent="#accordion">
        <div class="card card-body">
          <div class="container d-flex">
            <% if rec.photo.attached? %>
              <%= cl_image_tag rec.photo.key, class: "show-image" %>
            <% end %>
            <div class="ml-4 show-rec-card">
              <% if ['Show', 'Movie'].include? rec.category %>
                <div class="d-flex justify-content-between">
                  <div class="mr-4 pr-4">
                    <h1><%= rec.title %></h1>
                    <h6><%= rec.creator %></h6>
                  </div>
                  <div class="ml-4 mt-2 pl-4 text-right">
                    <h6>Year: <%= rec.duration %></h6>
                    <h6>IMDB: <%= rec.imdb_rating %>/10</h6>
                    <h6>Rotten Tomatoes: <%= rec.rt_rating %>%</h6>
                  </div>
                </div>
              <% else %>
                <div class="d-flex justify-content-between">
                  <div class="mr-4 pr-4">
                    <h1><%= rec.title %></h1>
                    <h6><%= rec.creator %></h6>
                  </div>
                  <div class="ml-4 mt-4 pl-4 text-right">
                    <h6>Year: <%= rec.duration %></h6>
                  </div>
                </div>
              <% end %>
              <h3 class="mt-4">Synopsis:</h3>
              <p><%= rec.synopsis %></p>
              <h3 class="mt-4">Why you should give it a shot:</h3>
              <p><%= rec.why %></p>
              <% if user_signed_in? %>
                <%= link_to edit_rec_path(rec) do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to rec_path(rec), method: :delete do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recs/_form.html.erb
<%= simple_form_for(@rec) do |f| %>
  <div class="row">
    <div class="col">
      <%= f.input :title %>
    </div>
    <div class="col">
      <%= f.input :creator, label: "Genres" %>
    </div>
  </div>
  <%= f.input :link %>
  <%= f.input :synopsis, :input_html => {:rows => 5} %>
  <%= f.input :why, :input_html => {:rows => 5} %>
  <div class="row">
    <div class="col">
      <%= f.input :imdb_rating, label: "IMDB Rating" %>
    </div>
    <div class="col">
      <%= f.input :rt_rating, label: "RT Rating" %>
    </div>
    <div class="col">
      <%= f.input :duration, label: "Year" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.input :release_date, as: :date, html5: true %>
    </div>
    <div class="col">
      <%= f.input :photo, label: "Poster", as: :file %>
    </div>
    <div class="col">
      <%= f.input :category, collection: @rec.rec_types %>
    </div>
  </div>
  <%= f.submit 'Submit' %>
<% end %>

app/views/recs/edit.html.erb
<div class="container">
  <div class="form-box">
    <%= render "form" %>
  </div>
</div>

app/views/recs/index.html.erb
<div class="container">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="true">All</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="movies-tab" data-toggle="tab" href="#movies" role="tab" aria-controls="movies" aria-selected="false">Movies</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="shows-tab" data-toggle="tab" href="#shows" role="tab" aria-controls="shows" aria-selected="false">Shows</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="books-tab" data-toggle="tab" href="#books" role="tab" aria-controls="books" aria-selected="false">Books</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="fanfics-tab" data-toggle="tab" href="#fanfics" role="tab" aria-controls="fanfics" aria-selected="false">Fanfics</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="games-tab" data-toggle="tab" href="#games" role="tab" aria-controls="games" aria-selected="false">Games</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="misc-tab" data-toggle="tab" href="#misc" role="tab" aria-controls="misc" aria-selected="false">Misc.</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
      <br><%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="movies" role="tabpanel" aria-labelledby="movies-tab">
      <br><% @recs = Rec.all_movies %>
      <%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="shows" role="tabpanel" aria-labelledby="shows-tab">
      <br><% @recs = Rec.all_shows %>
      <%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="books" role="tabpanel" aria-labelledby="books-tab">
      <br><% @recs = Rec.all_books %>
      <%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="fanfics" role="tabpanel" aria-labelledby="fanfics-tab">
      <br><% @recs = Rec.all_fanfics %>
      <%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="games" role="tabpanel" aria-labelledby="games-tab">
      <br><% @recs = Rec.all_games %>
      <%= render 'filter' %>
    </div>
    <div class="tab-pane fade" id="misc" role="tabpanel" aria-labelledby="misc-tab">
      <br><% @recs = Rec.all_misc %>
      <%= render 'filter' %>
    </div>
  </div>
</div>

app/views/recs/new.html.erb
<div class="container">
  <div class="form-box">
    <%= simple_form_for(@rec) do |f| %>
      <%= f.input :title %>
      <%= f.input :synopsis, :input_html => {:rows => 5} %>
      <%= f.input :why, :input_html => {:rows => 5} %>
      <%= f.input :creator %>
      <div class="row">
        <div class="col">
          <%= f.input :imdb_rating, label: "IMDB Rating" %>
        </div>
        <div class="col">
          <%= f.input :rt_rating, label: "RT Rating" %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.input :release_date, as: :date, html5: true %>
        </div>
        <div class="col">
          <%= f.input :photo, label: "Poster", as: :file %>
        </div>
      </div>
      <%= f.submit 'Submit' %>
    <% end %>
  </div>
</div>

app/views/recs/show.html.erb
<%= render "card", rec: @rec %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="text-right footer-lewagon d-flex justify-content-end">
  <p class="text-right">WEBSITE </p>
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete, class: "log-in-link pl-2 pr-2" do %>
      <i class="far fa-copyright"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "log-in-link pl-2 pr-2" do %>
      <i class="far fa-copyright"></i>
    <% end %>
  <% end %>
  <p> DIRECTTOANNE 2021</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon ml-4 mr-4 pl-4 pr-4">
  
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-white.png" %>
  <% end %>
  
  <li class="nav-item active">
    <%= link_to "PROJECTS", root_path(anchor: "projects"), class: "nav-link" %>
  </li>
  <li class="nav-item active">
    <%= link_to "FAQ", root_path(anchor: "faq"), class: "nav-link" %>
  </li>
  <li class="nav-item active">
    <%= link_to "CONTACT", root_path(anchor: "contact"), class: "nav-link" %>
  </li>
  <li class="nav-item active">
    <%= link_to "RECS", recs_path, class: "nav-link" %>
  </li>
  
</nav>